CREATE SEQUENCE SEQ_COLETA_LIXO
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE TBL_COLETA_LIXO (
    ID INTEGER DEFAULT SEQ_COLETA_LIXO.NEXTVAL NOT NULL,
    REGIAO VARCHAR2(100) NOT NULL,
    MOTORISTA VARCHAR2(20) NOT NULL,
    CAMINHAO VARCHAR2(20) NOT NULL,
    DATA_COLETA DATE NOT NULL
);